services:
  postgres:
    image: postgres:latest
    container_name: postgres-product
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_BD: produits

  adminer:
      image: adminer
      container_name: adminer
      restart: always
      ports:
        - 8080:8080
